version: '3.7'
services:

  front:
    container_name: webfront
    image: adryanleao/icotacao-front:1.0.5
    ports:
      - 8080:8080
    depends_on:
      - api
    restart: always

  api:
    container_name: webapi
    image: adryanleao/icotacao-backend:1.0.3
    build: .
    ports:
      - 4131:4131
    volumes:
      - ./:/app
    depends_on:
      - redis
      - mysql
    env_file: .env
    restart: always

  mysql:
    container_name: bancodados
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - ./initdb/dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sensi_db_init
    env_file: .env
    restart: always

  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    env_file: .env
    restart: always
