Description: Secrets

Resources:
  Github:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Github Registry Access
      Name: /Github
      SecretString: !Sub '{"username":"faravinicius","password":"739980ca50f696a648507ab6ad1285b464f785f3"}'

Outputs:
  GithubSecret:
    Description: Github Credentials for Docker Repository
    Value: !Ref Github
    Export:
      Name: GithubSecret
    