"""empty message

Revision ID: 00f46826bed4
Revises: 856947cd02b5
Create Date: 2021-01-26 10:24:33.971776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f46826bed4'
down_revision = '856947cd02b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_proposal_product', sa.Column('dont_stock', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_proposal_product', 'dont_stock')
    # ### end Alembic commands ###
