"""empty message

Revision ID: 0a2626ee6f52
Revises: 690ca8d40a56
Create Date: 2021-01-22 17:32:52.063510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2626ee6f52'
down_revision = '690ca8d40a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('quote_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification', 'quote', ['quote_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'quote_id')
    # ### end Alembic commands ###
