"""empty message

Revision ID: 0db633b35553
Revises: 20d7d737863e
Create Date: 2021-01-14 13:13:36.323412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0db633b35553'
down_revision = '20d7d737863e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('supplier_ibfk_1', 'supplier', type_='foreignkey')
    op.drop_column('supplier', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('supplier_ibfk_1', 'supplier', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
