"""empty message

Revision ID: 168716d0de2f
Revises: 00f46826bed4
Create Date: 2021-01-26 14:46:34.902251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168716d0de2f'
down_revision = '00f46826bed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_proposal', sa.Column('delivery_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_proposal', 'delivery_price')
    # ### end Alembic commands ###
