"""empty message

Revision ID: 1a6a757d66bc
Revises: 78b997ba4ded
Create Date: 2021-01-15 11:07:59.271469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a6a757d66bc'
down_revision = '78b997ba4ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_proposal_product', 'quantity')
    op.drop_column('quote_proposal_product', 'manufacturer')
    op.drop_column('quote_proposal_product', 'observation')
    op.drop_column('quote_proposal_product', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_proposal_product', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('quote_proposal_product', sa.Column('observation', mysql.TEXT(), nullable=True))
    op.add_column('quote_proposal_product', sa.Column('manufacturer', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('quote_proposal_product', sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
