"""empty message

Revision ID: 1b04fe0c2092
Revises: 4a33ee75c7a3
Create Date: 2021-01-14 10:44:55.725341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b04fe0c2092'
down_revision = '4a33ee75c7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='banner_image')
    op.drop_table('banner_image')
    op.drop_index('id', table_name='banner')
    op.drop_table('banner')
    op.drop_index('id', table_name='page_attachment')
    op.drop_table('page_attachment')
    op.drop_index('id', table_name='page')
    op.drop_table('page')
    op.drop_index('id', table_name='page_image')
    op.drop_table('page_image')
    op.alter_column('city', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('city', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('country', 'code_alpha3',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)
    op.alter_column('country', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('group', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('group', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_constraint('quote_ibfk_1', 'quote', type_='foreignkey')
    op.drop_column('quote', 'attachment_id')
    op.drop_constraint('quote_proposal_ibfk_1', 'quote_proposal', type_='foreignkey')
    op.drop_column('quote_proposal', 'attachment_id')
    op.drop_index('id', table_name='attachment')
    op.drop_table('attachment')
    op.alter_column('state', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('state', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'cell_phone',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'email_verified',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_column('user', 'cnpj')
    op.alter_column('user_address', 'code_post',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user_address', 'complement',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user_address', 'district',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user_address', 'number',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user_address', 'street',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_address', 'street',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user_address', 'number',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user_address', 'district',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user_address', 'complement',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user_address', 'code_post',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.add_column('user', sa.Column('cnpj', mysql.VARCHAR(length=256), nullable=True))
    op.alter_column('user', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'email_verified',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('user', 'cell_phone',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('state', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('state', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.add_column('quote_proposal', sa.Column('attachment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('quote_proposal_ibfk_1', 'quote_proposal', 'attachment', ['attachment_id'], ['id'])
    op.add_column('quote', sa.Column('attachment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('quote_ibfk_1', 'quote', 'attachment', ['attachment_id'], ['id'])
    op.alter_column('group', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('group', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('country', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('country', 'code_alpha3',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
    op.alter_column('city', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('city', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.create_table('page_image',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('code_internal', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('image_key', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('order_position', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'page_image', ['id'], unique=True)
    op.create_table('page',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.LONGTEXT(), nullable=True),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'page', ['id'], unique=True)
    op.create_table('page_attachment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('page_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('attachment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('file_key', mysql.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], name='page_attachment_ibfk_1'),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name='page_attachment_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'page_attachment', ['id'], unique=True)
    op.create_table('banner_image',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('banner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order_position', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('image_key', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('route', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('show_mobile', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('show_tablet', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('show_desktop', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['banner_id'], ['banner.id'], name='banner_image_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'banner_image', ['id'], unique=True)
    op.create_table('attachment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('slug', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('code_internal', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('file_key', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'attachment', ['id'], unique=True)
    op.create_table('banner',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('code_internal', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('order_position', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'banner', ['id'], unique=True)
    # ### end Alembic commands ###
