"""banner

Revision ID: 2347b34659f8
Revises: 117e1546859c
Create Date: 2020-12-24 11:43:32.575931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2347b34659f8'
down_revision = '117e1546859c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('code_internal', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('banner_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('banner_id', sa.Integer(), nullable=True),
    sa.Column('order_position', sa.Integer(), nullable=True),
    sa.Column('image_key', sa.String(length=256), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('route', sa.String(length=256), nullable=True),
    sa.Column('show_mobile', sa.Boolean(), nullable=True),
    sa.Column('show_tablet', sa.Boolean(), nullable=True),
    sa.Column('show_desktop', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banner_id'], ['banner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banner_image')
    op.drop_table('banner')
    # ### end Alembic commands ###
