"""empty message

Revision ID: 483304b69ff8
Revises: 4a291c3f0919
Create Date: 2021-01-14 20:16:30.976934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '483304b69ff8'
down_revision = '4a291c3f0919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costumer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('cell_phone', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('tax_payer', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('quote', sa.Column('costumer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quote', 'costumer', ['costumer_id'], ['id'])
    op.drop_column('quote', 'quote_type')
    op.drop_column('quote_product', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_product', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('quote', sa.Column('quote_type', mysql.VARCHAR(length=55), nullable=True))
    op.drop_constraint(None, 'quote', type_='foreignkey')
    op.drop_column('quote', 'costumer_id')
    op.drop_table('costumer')
    # ### end Alembic commands ###
