"""empty message

Revision ID: 4a291c3f0919
Revises: de43f213306b
Create Date: 2021-01-14 14:05:53.511277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a291c3f0919'
down_revision = 'de43f213306b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('receive_quotes', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('receive_quotes', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'receive_quotes')
    op.drop_column('company', 'receive_quotes')
    # ### end Alembic commands ###
