"""product_segment

Revision ID: 4a33ee75c7a3
Revises: a84199210695
Create Date: 2021-01-07 15:59:34.510913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a33ee75c7a3'
down_revision = 'a84199210695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_product', sa.Column('segment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quote_product', 'segment', ['segment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quote_product', type_='foreignkey')
    op.drop_column('quote_product', 'segment_id')
    # ### end Alembic commands ###
