"""empty message

Revision ID: 528e2e5f6bea
Revises: c11cc878a35d
Create Date: 2021-01-19 14:52:00.654794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528e2e5f6bea'
down_revision = 'c11cc878a35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('segment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quote', 'segment', ['segment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quote', type_='foreignkey')
    op.drop_column('quote', 'segment_id')
    # ### end Alembic commands ###
