"""empty message

Revision ID: 58e344bef73c
Revises: 0db633b35553
Create Date: 2021-01-14 13:15:04.950802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e344bef73c'
down_revision = '0db633b35553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'supplier', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'supplier_id')
    # ### end Alembic commands ###
