"""empty message

Revision ID: 690ca8d40a56
Revises: e2e9b9379efe
Create Date: 2021-01-22 15:24:55.399483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690ca8d40a56'
down_revision = 'e2e9b9379efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('quote_hash', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'quote_hash')
    # ### end Alembic commands ###
