"""empty message

Revision ID: 6bf793d42a4a
Revises: 483304b69ff8
Create Date: 2021-01-14 20:39:44.778652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bf793d42a4a'
down_revision = '483304b69ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('hash_id', table_name='user')
    op.drop_column('user', 'hash_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_id', mysql.VARCHAR(length=36), nullable=False))
    op.create_index('hash_id', 'user', ['hash_id'], unique=True)
    # ### end Alembic commands ###
