"""user_cnpj

Revision ID: 742ed23a682d
Revises: 5e47a248478c
Create Date: 2021-01-07 15:00:48.885917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742ed23a682d'
down_revision = '5e47a248478c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cnpj', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cnpj')
    # ### end Alembic commands ###
