"""empty message

Revision ID: 803182a3c665
Revises: 1b04fe0c2092
Create Date: 2021-01-14 11:39:52.215655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '803182a3c665'
down_revision = '1b04fe0c2092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    None
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    None
    # ### end Alembic commands ###
