"""empty message

Revision ID: a108cdefc054
Revises: 56b89baa3d11
Create Date: 2021-01-29 14:38:20.814997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a108cdefc054'
down_revision = '56b89baa3d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_product', sa.Column('product_hash', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_product', 'product_hash')
    # ### end Alembic commands ###
