"""quote_proposal

Revision ID: adc388b02e2f
Revises: beacf07d6bcb
Create Date: 2020-12-29 16:55:20.520295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc388b02e2f'
down_revision = 'beacf07d6bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_proposal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('proposal_type', sa.String(length=55), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_proposal')
    # ### end Alembic commands ###
