"""empty message

Revision ID: b5432bb4f89f
Revises: dc63e3a429a7
Create Date: 2021-01-14 21:24:57.001069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5432bb4f89f'
down_revision = 'dc63e3a429a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_product', sa.Column('name', sa.String(length=256), nullable=False))
    op.drop_column('quote_product', 'product_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_product', sa.Column('product_name', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('quote_product', 'name')
    # ### end Alembic commands ###
