"""empty message

Revision ID: bb2896d79184
Revises: 168716d0de2f
Create Date: 2021-01-26 15:53:17.037100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2896d79184'
down_revision = '168716d0de2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_proposal', sa.Column('shipping_included', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_proposal', 'shipping_included')
    # ### end Alembic commands ###
