"""empty message

Revision ID: bd79f6cc4c43
Revises: 803182a3c665
Create Date: 2021-01-14 11:42:44.726589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd79f6cc4c43'
down_revision = '803182a3c665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
