"""empty message

Revision ID: c11cc878a35d
Revises: 1a6a757d66bc
Create Date: 2021-01-15 14:20:01.897270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c11cc878a35d'
down_revision = '1a6a757d66bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_proposal', 'proposal_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_proposal', sa.Column('proposal_type', mysql.VARCHAR(length=55), nullable=True))
    # ### end Alembic commands ###
