"""empty message

Revision ID: c6755b4a5cb6
Revises: 6bf793d42a4a
Create Date: 2021-01-14 21:05:49.182775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6755b4a5cb6'
down_revision = '6bf793d42a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'file_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('file_key', mysql.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
